export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

//Selected current Restaurant
export const SELECTED_RESTAURANT_ID = 'SELECTED_RESTAURANT_ID';
//Selected Menu
export const SELECTED_MENU_ID = 'SELECTED_MENU_ID';

//Restaurant CRUD TYPE
export const CREATE_TUTORIAL = 'CREATE_TUTORIAL';
export const RETRIEVE_TUTORIALS = 'RETRIEVE_TUTORIALS';
export const UPDATE_TUTORIAL = 'UPDATE_TUTORIAL';
export const DELETE_TUTORIAL = 'DELETE_TUTORIAL';
export const DELETE_ALL_TUTORIALS = 'DELETE_ALL_TUTORIALS';
export const ADD_ACCESS_TOKEN = 'ADD_ACCESS_TOKEN';

//MODAL
export const MODAL_CLOSE = 'MODAL_CLOSE';
export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_STATUS = 'MODAL_STATUS';

//ALERT MESSAGE
export const SUCCESS_ALERT = 'SUCCESS_ALERT';
export const FAILED_ALERT = 'FAILED_ALERT';
